[build]
command = "npm run build -w demos/next-with-edge-functions"
publish = "demos/next-with-edge-functions/.next"

[[plugins]]
package = "@netlify/plugin-nextjs"

# This is a fake plugin, that makes it run npm install
[[plugins]]
package = "@netlify/plugin-local-install-core"

[[plugins]]
package = "./demos/plugin-wrapper"
