name: Run e2e (edge router)
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
  push:
    branches:
      - main
    paths:
      - 'test/e2e/router/**/*.{js,jsx,ts,tsx}'
      - 'demos/custom-routes/**/*'
      - 'packages/**/*.{ts,js}'
jobs:
  vitest:
    name: Vitest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Github token
        uses: navikt/github-app-token-generator@v1
        id: get-token
        with:
          private-key: ${{ secrets.TOKENS_PRIVATE_KEY }}
          app-id: ${{ secrets.TOKENS_APP_ID }}

      - name: Checkout @netlify/wait-for-deploy-action
        uses: actions/checkout@v2
        with:
          repository: netlify/wait-for-deploy-action
          token: ${{ steps.get-token.outputs.token }}
          path: ./.github/actions/wait-for-netlify-deploy

      - name: Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'

      - name: Install npm dependencies
        run: npm install

      - name: Install Playwright dependencies
        run: npm run playwright:install

      - name: Wait for Netlify Deploy
        id: deploy
        uses: ./.github/actions/wait-for-netlify-deploy
        with:
          site-name: nextjs-plugin-custom-routes-demo
          timeout: 300

      - name: Deploy successful
        if: ${{ steps.deploy.outputs.origin-url }}
        run: echo ${{ steps.deploy.outputs.origin-url }}

      - name: Run e2e tests
        if: ${{ steps.deploy.outputs.origin-url }}
        run: npm run test:e2e -- tests/e2e/router
        env:
          SITE_URL: ${{ steps.deploy.outputs.origin-url }}
