[build]
command = "next build"
publish = ".next"
ignore = "if [ $CACHED_COMMIT_REF == $COMMIT_REF ]; then (exit 1); else git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ../..; fi;"

[build.environment]
NETLIFY_NEXT_EDGE_ROUTER = "true"

[dev]
framework = "#static"

[[plugins]]
package = "../plugin-wrapper/"

[[plugins]]
package = "@netlify/plugin-local-install-core"
# [[context.deploy-preview.plugins]]
# package = "netlify-plugin-cypress"
